-- Agrega el Jefe de Zona (JDZ) al catálogo de tiendas, para poder generar
-- las etiquetas de envío (Tienda, Departamento, Jefe de Zona, Insumo, Fecha).

alter table public.tiendas add column if not exists jdz text;

update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'DORADA 4';
update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'DORADA ALPES';
update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'DORADA CENTRO';
update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'DORADA FERIAS';
update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'DORADA PALMAS';
update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'NORCASIA';
update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'PTO SALGAR';
update public.tiendas set jdz = 'CRISTIAN ANDRADE' where nombre = 'PUERTO SALGAR BASE AEREA';
update public.tiendas set jdz = 'ALEJANDRA GALINDO' where nombre = 'SAMANA';
update public.tiendas set jdz = 'ALEJANDRA GALINDO' where nombre = 'VICTORIA';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'CAQ BELEN';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'CAQ CHAIRA CENTRO';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'CAQ COLONOS';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'CAQ EL PAUJIL';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'CAQ PUERTO RICO';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'CAQ SAN VICEN CAGUAN';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'CAQ SAN VICEN JARDIN';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'DONCELLO';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'FLORENCIA CALLE 21';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'FLORENCIA CIUDADELA';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'FLORENCIA GALERIA';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'FLORENCIA PALO A';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'FLORENCIA TRONCAL';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'FLORENCIA CENTRO';
update public.tiendas set jdz = 'ALEX CIFUENTES' where nombre = 'FLORENCIA SATELITE';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT AV BAVARIA';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT AV KENNEDY';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT AV NARIÑO';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT CAMELLON';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT CRA 10';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT EL PEÑON';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT GAITAN';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'GIRARDOT GRANADA';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'RICAURTE BULEVAR';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'RICAURTE PEÑALISA';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'TOLEMAIDA';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'AVENIDA PASTRANA';
update public.tiendas set jdz = 'STITH MORALES' where nombre = 'GARZON CENTRO';
update public.tiendas set jdz = 'STITH MORALES' where nombre = 'GIGANTE';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'HUILA ACEVEDO';
update public.tiendas set jdz = 'STITH MORALES' where nombre = 'HUILA AGRADO';
update public.tiendas set jdz = 'STITH MORALES' where nombre = 'HUILA CAMPO ALEGRE';
update public.tiendas set jdz = 'STITH MORALES' where nombre = 'HUILA GARZON';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'HUILA GUADALUPE';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'HUILA ISNOS';
update public.tiendas set jdz = 'RICARDO HIDALGO' where nombre = 'HUILA LA PLATA';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'HUILA PALERMO';
update public.tiendas set jdz = 'STITH MORALES' where nombre = 'HUILA RIVERA';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'HUILA SUAZA';
update public.tiendas set jdz = 'RICARDO HIDALGO' where nombre = 'HUILA TESALIA';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'HUILA TIMANA';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'PITALITO BRUSELAS';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'PITALITO CENTRO';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'PITALITO PALESTINA';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'PITALITO PLAZA CIVICA';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'PITALITO VILLA SOFIA';
update public.tiendas set jdz = 'DIXON MUÑOZ' where nombre = 'SAN AGUSTIN';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'HUILA AIPE';
update public.tiendas set jdz = 'CARLOS MARTINEZ' where nombre = 'CANTABRIA';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE AMBALA ALTA';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE ANCON';
update public.tiendas set jdz = 'CARLOS MARTINEZ' where nombre = 'IBAGUE ANTONIO NARIÑO';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE ARRAYANES';
update public.tiendas set jdz = 'LORENA TRILLERAS' where nombre = 'IBAGUE BARLOVENTO';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE CALLE 19';
update public.tiendas set jdz = 'CARLOS MARTINEZ' where nombre = 'IBAGUE CALLE 42';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE CL 60 AMBALA';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE CRA 5';
update public.tiendas set jdz = 'LORENA TRILLERAS' where nombre = 'IBAGUE DISTRITO 60';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE EL JARDIN';
update public.tiendas set jdz = 'CARLOS MARTINEZ' where nombre = 'IBAGUE EL SALADO';
update public.tiendas set jdz = 'LORENA TRILLERAS' where nombre = 'IBAGUE FILADELFIA';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE FRONTERA';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE GAITANA';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE GODOY';
update public.tiendas set jdz = 'CARLOS MARTINEZ' where nombre = 'IBAGUE JORDAN CR 5';
update public.tiendas set jdz = 'LORENA TRILLERAS' where nombre = 'IBAGUE LA FLORIDA';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE LA GAVIOTA';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE LA POLA';
update public.tiendas set jdz = '#N/A' where nombre = 'IBAGUE M30';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE MONTECARLO';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE PANOPTICO';
update public.tiendas set jdz = 'LORENA TRILLERAS' where nombre = 'IBAGUE PIEDRAPINTADA';
update public.tiendas set jdz = 'LORENA TRILLERAS' where nombre = 'IBAGUE POBLADO';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE RICAURTE';
update public.tiendas set jdz = 'DUVAN GALINDO' where nombre = 'IBAGUE SAN PEDRO';
update public.tiendas set jdz = 'GREGORIO GUARNIZO' where nombre = 'IBAGUE SANTA ANA';
update public.tiendas set jdz = 'CARLOS MARTINEZ' where nombre = 'IBAGUE VARSOVIA';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'NEIVA 6W';
update public.tiendas set jdz = 'RICARDO HIDALGO' where nombre = 'NEIVA ACQUA VIVA';
update public.tiendas set jdz = 'VANESA RIOBO' where nombre = 'NEIVA ALTICO';
update public.tiendas set jdz = 'RICARDO HIDALGO' where nombre = 'NEIVA BELLAVISTA';
update public.tiendas set jdz = 'VANESA RIOBO' where nombre = 'NEIVA BUGANVILES';
update public.tiendas set jdz = 'VANESA RIOBO' where nombre = 'NEIVA CALIXTO';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'NEIVA CALLE 2';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'NEIVA CANDIDO';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'NEIVA CENTRO';
update public.tiendas set jdz = 'VANESA RIOBO' where nombre = 'NEIVA COMUNEROS';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'NEIVA GALINDO';
update public.tiendas set jdz = 'ADRIAN MORA' where nombre = 'NEIVA INMACULADA';
update public.tiendas set jdz = 'VANESA RIOBO' where nombre = 'NEIVA IPANEMA';
update public.tiendas set jdz = 'VANESA RIOBO' where nombre = 'NEIVA LAS BRISAS';
update public.tiendas set jdz = 'RICARDO HIDALGO' where nombre = 'NEIVA LAS GRANJAS';
update public.tiendas set jdz = 'VANESA RIOBO' where nombre = 'NEIVA LAS PALMAS';
update public.tiendas set jdz = 'RICARDO HIDALGO' where nombre = 'NEIVA PTA DEL SOL';
update public.tiendas set jdz = 'STITH MORALES' where nombre = 'NEIVA TENERIFE';
update public.tiendas set jdz = 'RICARDO HIDALGO' where nombre = 'NEIVA TIMANCO';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'HORMIGA PUTUMAYO';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'MOCOA AV COLOMBIA';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'MOCOA CENTRO';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'MOCOA PABLO VI';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'ORITO PUTUMAYO';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'PUERTO ASIS CENTRO';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'PUERTO ASIS KENNEDY';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'SAN MIGUEL PUTUMAYO';
update public.tiendas set jdz = 'MIGUEL LOZADA' where nombre = 'VILLAGARZON PUTUMAYO';
update public.tiendas set jdz = 'ALVARO BORJA' where nombre = 'AMBALEMA';
update public.tiendas set jdz = 'ALVARO BORJA' where nombre = 'ARMERO GUAYABAL';
update public.tiendas set jdz = 'CARLOS MARTINEZ' where nombre = 'CAJAMARCA';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'CARMEN D APICALA';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'FLANDES AV PANAMERICANA';
update public.tiendas set jdz = 'ALEJANDRA GALINDO' where nombre = 'HONDA CENTENARIO';
update public.tiendas set jdz = 'ALEJANDRA GALINDO' where nombre = 'HONDA SANTA BARBARA';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'MELGAR CENTRO';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'MELGAR SICOMORO';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'MELGAR SULTANA';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'MELGAR VERSALLES';
update public.tiendas set jdz = 'ALEJANDRA GALINDO' where nombre = 'TOL FRESNO';
update public.tiendas set jdz = 'ALEJANDRA GALINDO' where nombre = 'TOL HONDA';
update public.tiendas set jdz = 'ALVARO BORJA' where nombre = 'TOL LERIDA CENTRO';
update public.tiendas set jdz = 'ALVARO BORJA' where nombre = 'TOL LIBANO';
update public.tiendas set jdz = 'ALVARO BORJA' where nombre = 'TOL MARIQUITA';
update public.tiendas set jdz = 'ALVARO BORJA' where nombre = 'TOL MARIQUITA DORADO';
update public.tiendas set jdz = 'ALEXANDER PAEZ' where nombre = 'TOLIMA FLANDES';
update public.tiendas set jdz = 'LORENA TRILLERAS' where nombre = 'TOLIMA ROVIRA';
update public.tiendas set jdz = 'ALVARO BORJA' where nombre = 'VENADILLO CENTRO';
update public.tiendas set jdz = 'ALEJANDRA GALINDO' where nombre = 'FRESNO PLAZA';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'ATACO';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'CHAPARRAL CENTRO';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'CHAPARRAL SIMON BOLIVAR';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'CHICORAL';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'COYAIMA';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'ESPINAL CENTRO';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'ESPINAL LA TAMBORA';
update public.tiendas set jdz = 'CRISTIAN TAPIA' where nombre = 'ESPINAL PLAZA';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'GUAMO';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'GUAMO CENTRO';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'TOL PLANADAS GALERIA';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'TOLIMA NATAGAIMA';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'TOLIMA PURIFICACIÓN';
update public.tiendas set jdz = 'ANGELA DIAZ' where nombre = 'TOLIMA SALDAÑA';
